# Generated by Django 3.2.4 on 2021-06-26 19:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0002_product_product_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_quantity_type',
            field=models.CharField(choices=[('250GM', '250 Grams'), ('500GM', '500 Grams'), ('750GM', '750 Grams'), ('1000GM', '1 Kg'), ('1PC', '1 Pc'), ('12PC', '12 Pc')], max_length=6),
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wishlist_created', models.DateTimeField(auto_now_add=True)),
                ('wishlist_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('wishlist_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
